In [2]:
!pip3 install covsirphy --upgrade

Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
Collecting covsirphy
  Downloading covsirphy-2.7.0-py3-none-any.whl (119 kB)
     |████████████████████████████████| 119 kB 760 kB/s eta 0:00:01
Collecting covid19dh
  Downloading covid19dh-1.0.0-py3-none-any.whl (20 kB)
Requirement already satisfied, skipping upgrade: seaborn in /home/nnbtam99/.local/lib/python3.8/site-packages (from covsirphy) (0.10.1)
Collecting dask[complete]
  Downloading dask-2.23.0-py3-none-any.whl (831 kB)
     |████████████████████████████████| 831 kB 1.8 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: numpy in /home/nnbtam99/.local/lib/python3.8/site-packages (from covsirphy) (1.19.0)
Collecting better-exceptions
  Downloading better_exceptions-0.2.2-py3-none-any.whl (11 kB)
Collecting optuna
  Downloading optuna-2.0.0.tar.gz (226 kB)
     |████████████████████████████████| 226 kB 2.4 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from covsirphy) (2.22.0)
Requirement already satisfied, skipping upgrade: pandas in /home/nnbtam99/.local/lib/python3.8/site-packages (from covsirphy) (1.0.5)
Requirement already satisfied, skipping upgrade: scikit-learn in /home/nnbtam99/.local/lib/python3.8/site-packages (from covsirphy) (0.23.1)
Requirement already satisfied, skipping upgrade: scipy in /home/nnbtam99/.local/lib/python3.8/site-packages (from covsirphy) (1.5.1)
Collecting japanmap
  Downloading japanmap-0.0.22-py3-none-any.whl (166 kB)
     |████████████████████████████████| 166 kB 2.6 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: matplotlib in /home/nnbtam99/.local/lib/python3.8/site-packages (from covsirphy) (3.2.2)
Collecting ruptures
  Downloading ruptures-1.0.5-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 1.3 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: pyyaml in /usr/lib/python3/dist-packages (from dask[complete]->covsirphy) (5.3.1)
Collecting cloudpickle>=0.2.2; extra == "complete"
  Downloading cloudpickle-1.5.0-py3-none-any.whl (22 kB)
Collecting partd>=0.3.10; extra == "complete"
  Downloading partd-1.1.0-py3-none-any.whl (19 kB)
Collecting bokeh>=1.0.0; extra == "complete"
  Downloading bokeh-2.1.1.tar.gz (19.3 MB)
     |████████████████████████████████| 19.3 MB 405 kB/s eta 0:00:01
Collecting toolz>=0.8.2; extra == "complete"
  Downloading toolz-0.10.0.tar.gz (49 kB)
     |████████████████████████████████| 49 kB 850 kB/s eta 0:00:01
Collecting fsspec>=0.6.0; extra == "complete"
  Downloading fsspec-0.8.0-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 950 kB/s eta 0:00:01
Collecting distributed>=2.0; extra == "complete"
  Downloading distributed-2.23.0-py3-none-any.whl (650 kB)
     |████████████████████████████████| 650 kB 1.3 MB/s eta 0:00:01
Processing /home/nnbtam99/.cache/pip/wheels/70/08/70/cea787a7e95817b831469fa42af076046e55a05f7c94657463/alembic-1.4.2-py2.py3-none-any.whl
Collecting cliff
  Downloading cliff-3.4.0-py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 1.5 MB/s eta 0:00:01
Collecting cmaes>=0.5.1
  Downloading cmaes-0.6.0-py3-none-any.whl (9.6 kB)
Collecting colorlog
  Downloading colorlog-4.2.1-py2.py3-none-any.whl (14 kB)
Requirement already satisfied, skipping upgrade: joblib in /home/nnbtam99/.local/lib/python3.8/site-packages (from optuna->covsirphy) (0.16.0)
Requirement already satisfied, skipping upgrade: packaging in /home/nnbtam99/.local/lib/python3.8/site-packages (from optuna->covsirphy) (20.4)
Requirement already satisfied, skipping upgrade: sqlalchemy>=1.1.0 in /home/nnbtam99/.local/lib/python3.8/site-packages (from optuna->covsirphy) (1.3.18)
Requirement already satisfied, skipping upgrade: tqdm in /home/nnbtam99/.local/lib/python3.8/site-packages (from optuna->covsirphy) (4.48.2)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /usr/lib/python3/dist-packages (from pandas->covsirphy) (2.7.3)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas->covsirphy) (2019.3)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in /home/nnbtam99/.local/lib/python3.8/site-packages (from scikit-learn->covsirphy) (2.1.0)
Requirement already satisfied, skipping upgrade: opencv-python<5.0.0,>=4.2.0 in /home/nnbtam99/.local/lib/python3.8/site-packages (from japanmap->covsirphy) (4.3.0.36)
Collecting Pillow<8.0.0,>=7.1.1
  Using cached Pillow-7.2.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /home/nnbtam99/.local/lib/python3.8/site-packages (from matplotlib->covsirphy) (0.10.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /home/nnbtam99/.local/lib/python3.8/site-packages (from matplotlib->covsirphy) (1.2.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/nnbtam99/.local/lib/python3.8/site-packages (from matplotlib->covsirphy) (2.4.7)
Collecting locket
  Downloading locket-0.2.0.tar.gz (3.5 kB)
Requirement already satisfied, skipping upgrade: Jinja2>=2.7 in /home/nnbtam99/.local/lib/python3.8/site-packages (from bokeh>=1.0.0; extra == "complete"->dask[complete]->covsirphy) (2.11.2)
Requirement already satisfied, skipping upgrade: tornado>=5.1 in /home/nnbtam99/.local/lib/python3.8/site-packages (from bokeh>=1.0.0; extra == "complete"->dask[complete]->covsirphy) (6.0.4)
Collecting typing_extensions>=3.7.4
  Downloading typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Collecting psutil>=5.0
  Downloading psutil-5.7.2.tar.gz (460 kB)
     |████████████████████████████████| 460 kB 1.5 MB/s eta 0:00:01
Collecting zict>=0.1.3
  Downloading zict-2.0.0-py3-none-any.whl (10 kB)
Collecting sortedcontainers!=2.0.0,!=2.0.1
  Downloading sortedcontainers-2.2.2-py2.py3-none-any.whl (29 kB)
Requirement already satisfied, skipping upgrade: click>=6.6 in /home/nnbtam99/.local/lib/python3.8/site-packages (from distributed>=2.0; extra == "complete"->dask[complete]->covsirphy) (7.1.2)
Collecting msgpack>=0.6.0
  Downloading msgpack-1.0.0-cp38-cp38-manylinux1_x86_64.whl (303 kB)
     |████████████████████████████████| 303 kB 1.0 MB/s eta 0:00:01
Collecting tblib>=1.6.0
  Downloading tblib-1.7.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3/dist-packages (from distributed>=2.0; extra == "complete"->dask[complete]->covsirphy) (45.2.0)
Collecting python-editor>=0.3
  Using cached python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Requirement already satisfied, skipping upgrade: Mako in /usr/lib/python3/dist-packages (from alembic->optuna->covsirphy) (1.1.0)
Collecting pbr!=2.1.0,>=2.0.0
  Downloading pbr-5.4.5-py2.py3-none-any.whl (110 kB)
     |████████████████████████████████| 110 kB 1.5 MB/s eta 0:00:01
Collecting cmd2!=0.8.3,>=0.8.0
  Downloading cmd2-1.3.3-py3-none-any.whl (130 kB)
     |████████████████████████████████| 130 kB 1.7 MB/s eta 0:00:01
Collecting PrettyTable<0.8,>=0.7.2
  Downloading prettytable-0.7.2.tar.bz2 (21 kB)
Collecting stevedore>=2.0.1
  Downloading stevedore-3.2.0-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.1 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3/dist-packages (from cliff->optuna->covsirphy) (1.14.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.7->bokeh>=1.0.0; extra == "complete"->dask[complete]->covsirphy) (1.1.0)
Collecting heapdict
  Downloading HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Requirement already satisfied, skipping upgrade: attrs>=16.3.0 in /home/nnbtam99/.local/lib/python3.8/site-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna->covsirphy) (19.3.0)
Collecting colorama>=0.3.7
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting pyperclip>=1.6
  Downloading pyperclip-1.8.0.tar.gz (16 kB)
Requirement already satisfied, skipping upgrade: wcwidth>=0.1.7 in /home/nnbtam99/.local/lib/python3.8/site-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna->covsirphy) (0.2.5)
Building wheels for collected packages: optuna, bokeh, toolz, locket, psutil, PrettyTable, pyperclip
  Building wheel for optuna (setup.py) ... done
  Created wheel for optuna: filename=optuna-2.0.0-py3-none-any.whl size=312846 sha256=bf1e31c7a64835c7078148ddd6ab60cb97790ee6cdd3746f78ce83eb8f9477fb
  Stored in directory: /home/nnbtam99/.cache/pip/wheels/4d/a4/b5/5924180fbed08f1cd115effffd504186ebeb31bd32ff4eff3b
  Building wheel for bokeh (setup.py) ... done
  Created wheel for bokeh: filename=bokeh-2.1.1-py3-none-any.whl size=9257189 sha256=13a917f5c9cd348e09e230926ea0f168cb07c7bae136392a6a1b671db7d10c5a
  Stored in directory: /home/nnbtam99/.cache/pip/wheels/6f/1b/bc/5add06a501c46e8aee615a089555beffdad8030aa5d6d35830
  Building wheel for toolz (setup.py) ... done
  Created wheel for toolz: filename=toolz-0.10.0-py3-none-any.whl size=55575 sha256=79b0e461f00d049d24b00a00735d4017c976957a410a13894b803258221d1030
  Stored in directory: /home/nnbtam99/.cache/pip/wheels/a5/2b/b5/05758d5828d65f2adef8fbb5d5484e4adb946ae1827a973a01
  Building wheel for locket (setup.py) ... done
  Created wheel for locket: filename=locket-0.2.0-py3-none-any.whl size=4038 sha256=5d399fafb22d28433b0d731a7f1750d9dd6bcdad777c27aead2585e1261cba2c
  Stored in directory: /home/nnbtam99/.cache/pip/wheels/78/25/55/fd7749af1f37730049bf1c0c0f4efd755c4ab1399f29578436
  Building wheel for psutil (setup.py) ... done
  Created wheel for psutil: filename=psutil-5.7.2-cp38-cp38-linux_x86_64.whl size=293026 sha256=6685184b67999d6f1a8e4bbcba93449a7d759360d4191dd790bda0fa359b40e9
  Stored in directory: /home/nnbtam99/.cache/pip/wheels/91/cf/b0/0c9998060b55ca80ea7a50a8639c3bdc6ba886eeff014bc9ac
  Building wheel for PrettyTable (setup.py) ... done
  Created wheel for PrettyTable: filename=prettytable-0.7.2-py3-none-any.whl size=13698 sha256=62c324d06d26f5306912a465719f373891bc33e922859bfc88fe207bd706eab2
  Stored in directory: /home/nnbtam99/.cache/pip/wheels/46/60/6c/bb25d05df22906786206e901e9354bb3061061191116768bee
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.0-py3-none-any.whl size=8691 sha256=1a7571de394c37cb71adfd97a23ea997617a408954b166bad610b2e59608f524
  Stored in directory: /home/nnbtam99/.cache/pip/wheels/03/79/58/ab51f0f590281b0f4f6046d9271eb98cc50565afb9200f155a
Successfully built optuna bokeh toolz locket psutil PrettyTable pyperclip
Installing collected packages: covid19dh, cloudpickle, locket, toolz, partd, Pillow, typing-extensions, bokeh, fsspec, psutil, heapdict, zict, sortedcontainers, msgpack, tblib, distributed, dask, better-exceptions, python-editor, alembic, pbr, colorama, pyperclip, cmd2, PrettyTable, stevedore, cliff, cmaes, colorlog, optuna, japanmap, ruptures, covsirphy
Successfully installed Pillow-7.2.0 PrettyTable-0.7.2 alembic-1.4.2 better-exceptions-0.2.2 bokeh-2.1.1 cliff-3.4.0 cloudpickle-1.5.0 cmaes-0.6.0 cmd2-1.3.3 colorama-0.4.3 colorlog-4.2.1 covid19dh-1.0.0 covsirphy-2.7.0 dask-2.23.0 distributed-2.23.0 fsspec-0.8.0 heapdict-1.0.1 japanmap-0.0.22 locket-0.2.0 msgpack-1.0.0 optuna-2.0.0 partd-1.1.0 pbr-5.4.5 psutil-5.7.2 pyperclip-1.8.0 python-editor-1.0.4 ruptures-1.0.5 sortedcontainers-2.2.2 stevedore-3.2.0 tblib-1.7.0 toolz-0.10.0 typing-extensions-3.7.4.2 zict-2.0.0

In [4]:
!pip3 install wget

Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
Collecting wget
  Downloading wget-3.2.zip (10 kB)
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9681 sha256=c784c624694c2cd4de5d75821d13680eb46c8ee18aad830a69893380432bc468
  Stored in directory: /home/nnbtam99/.cache/pip/wheels/bd/a8/c3/3cf2c14a1837a4e04bd98631724e81f33f462d86a1d895fae0
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

In [5]:
import covsirphy as cvp
import pandas as pd
import numpy as np
import wget # to download data

In [6]:
urls = ['https://raw.githubusercontent.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning/master/covid_19_clean_complete.csv',
       'https://raw.githubusercontent.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning/master/full_grouped.csv',
       'https://raw.githubusercontent.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning/master/time_series_covid19_deaths_US.csv']

for url in urls:
    filename = wget.download(url)

In [7]:
data = pd.read_csv('covid_19_clean_complete.csv')

In [8]:
data_us = data[data['Country/Region'] == 'US']

In [9]:
data_us = data_us.drop(columns=['Province/State', 'Country/Region', 'Lat', 'Long', 'WHO Region'], axis=1)

In [10]:
data_us.head(1)

           Date  Confirmed  Deaths  Recovered  Active
223  2020-01-22          1       0          0       1

In [11]:
data = pd.read_csv('full_grouped.csv')

In [12]:
data_us1 = data[data['Country/Region'] == 'US'].reset_index()

In [13]:
data_us1.head(20)

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
0,173,2020-01-22,US,1,0,0,1,0,0,0,Americas
1,360,2020-01-23,US,1,0,0,1,0,0,0,Americas
2,547,2020-01-24,US,2,0,0,2,1,0,0,Americas
3,734,2020-01-25,US,2,0,0,2,0,0,0,Americas
4,921,2020-01-26,US,5,0,0,5,3,0,0,Americas
5,1108,2020-01-27,US,5,0,0,5,0,0,0,Americas
6,1295,2020-01-28,US,5,0,0,5,0,0,0,Americas
7,1482,2020-01-29,US,5,0,0,5,0,0,0,Americas
8,1669,2020-01-30,US,5,0,0,5,0,0,0,Americas
9,1856,2020-01-31,US,7,0,0,7,2,0,0,Americas
10,2043,2020-02-01,US,8,0,0,8,1,0,0,Americas
11,2230,2020-02-02,US,8,0,0,8,0,0,0,Americas
12,2417,2020-02-03,US,11,0,0,11,3,0,0,Americas
13,2604,2020-02-04,US,11,0,0,11,0,0,0,Americas
14,2791,2020-02-05,US,11,0,0,11,0,0,0,Americas
15,2978,2020-02-06,US,11,0,0,11,0,0,0,Americas
16,3165,2020-02-07,US,11,0,0,11,0,0,0,Americas
17,3352,2020-02-08,US,11,0,0,11,0,0,0,Americas
18,3539,2020-02-09,US,11,0,3,8,0,0,3,Americas
19,3726,2020-02-10,US,11,0,3,8,0,0,0,Americas

In [14]:
df = pd.read_csv('time_series_covid19_deaths_US.csv')

In [15]:
population = df['Population'].sum()

In [16]:
population

339573798

In [17]:
num_sample = len(data_us1)

In [18]:
population = [population for _ in range(num_sample)]

In [19]:
data_us1['Population'] = population

In [20]:
data_us1.head(5)

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population
0,173,2020-01-22,US,1,0,0,1,0,0,0,Americas,339573798
1,360,2020-01-23,US,1,0,0,1,0,0,0,Americas,339573798
2,547,2020-01-24,US,2,0,0,2,1,0,0,Americas,339573798
3,734,2020-01-25,US,2,0,0,2,0,0,0,Americas,339573798
4,921,2020-01-26,US,5,0,0,5,3,0,0,Americas,339573798

In [21]:
data_us1.head(100)

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population
0,173,2020-01-22,US,1,0,0,1,0,0,0,Americas,339573798
1,360,2020-01-23,US,1,0,0,1,0,0,0,Americas,339573798
2,547,2020-01-24,US,2,0,0,2,1,0,0,Americas,339573798
3,734,2020-01-25,US,2,0,0,2,0,0,0,Americas,339573798
4,921,2020-01-26,US,5,0,0,5,3,0,0,Americas,339573798
...,...,...,...,...,...,...,...,...,...,...,...,...
95,17938,2020-04-26,US,968518,55810,106988,805720,27689,1293,6616,Americas,339573798
96,18125,2020-04-27,US,990983,57235,111424,822324,22465,1425,4436,Americas,339573798
97,18312,2020-04-28,US,1015518,59454,115936,840128,24535,2219,4512,Americas,339573798
98,18499,2020-04-29,US,1043038,61960,120720,860358,27520,2506,4784,Americas,339573798
99,18686,2020-04-30,US,1072667,64256,153947,854464,29629,2296,33227,Americas,339573798

In [22]:
data_us1['Susceptiple'] = data_us1['Population'] - data_us1['Confirmed']

In [23]:
data_us1['Log susceptiple'] = np.log(data_us1['Susceptiple'])

In [24]:
data_us1.head(15)

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population,Susceptiple,Log susceptiple
0,173,2020-01-22,US,1,0,0,1,0,0,0,Americas,339573798,339573797,19.643202
1,360,2020-01-23,US,1,0,0,1,0,0,0,Americas,339573798,339573797,19.643202
2,547,2020-01-24,US,2,0,0,2,1,0,0,Americas,339573798,339573796,19.643202
3,734,2020-01-25,US,2,0,0,2,0,0,0,Americas,339573798,339573796,19.643202
4,921,2020-01-26,US,5,0,0,5,3,0,0,Americas,339573798,339573793,19.643202
5,1108,2020-01-27,US,5,0,0,5,0,0,0,Americas,339573798,339573793,19.643202
6,1295,2020-01-28,US,5,0,0,5,0,0,0,Americas,339573798,339573793,19.643202
7,1482,2020-01-29,US,5,0,0,5,0,0,0,Americas,339573798,339573793,19.643202
8,1669,2020-01-30,US,5,0,0,5,0,0,0,Americas,339573798,339573793,19.643202
9,1856,2020-01-31,US,7,0,0,7,2,0,0,Americas,339573798,339573791,19.643202
10,2043,2020-02-01,US,8,0,0,8,1,0,0,Americas,339573798,339573790,19.643202
11,2230,2020-02-02,US,8,0,0,8,0,0,0,Americas,339573798,339573790,19.643202
12,2417,2020-02-03,US,11,0,0,11,3,0,0,Americas,339573798,339573787,19.643202
13,2604,2020-02-04,US,11,0,0,11,0,0,0,Americas,339573798,339573787,19.643202
14,2791,2020-02-05,US,11,0,0,11,0,0,0,Americas,339573798,339573787,19.643202

In [25]:
susceptiple = np.asarray(data_us1['Susceptiple'])

In [26]:
new_susceptiple = susceptiple[:-1] - susceptiple[1:]

In [27]:
new_susceptiple = np.insert(new_susceptiple, 0, 0)

In [28]:
data_us1['Decresed susceptiple'] = new_susceptiple

In [29]:
data_us1.head(100)

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population,Susceptiple,Log susceptiple,Decresed susceptiple
0,173,2020-01-22,US,1,0,0,1,0,0,0,Americas,339573798,339573797,19.643202,0
1,360,2020-01-23,US,1,0,0,1,0,0,0,Americas,339573798,339573797,19.643202,0
2,547,2020-01-24,US,2,0,0,2,1,0,0,Americas,339573798,339573796,19.643202,1
3,734,2020-01-25,US,2,0,0,2,0,0,0,Americas,339573798,339573796,19.643202,0
4,921,2020-01-26,US,5,0,0,5,3,0,0,Americas,339573798,339573793,19.643202,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,17938,2020-04-26,US,968518,55810,106988,805720,27689,1293,6616,Americas,339573798,338605280,19.640346,27689
96,18125,2020-04-27,US,990983,57235,111424,822324,22465,1425,4436,Americas,339573798,338582815,19.640279,22465
97,18312,2020-04-28,US,1015518,59454,115936,840128,24535,2219,4512,Americas,339573798,338558280,19.640207,24535
98,18499,2020-04-29,US,1043038,61960,120720,860358,27520,2506,4784,Americas,339573798,338530760,19.640126,27520
99,18686,2020-04-30,US,1072667,64256,153947,854464,29629,2296,33227,Americas,339573798,338501131,19.640038,29629

In [30]:
data_us1 = data_us1.drop(columns=['WHO Region', 'Country/Region'])

In [31]:
data_us1.head(10)

,index,Date,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Population,Susceptiple,Log susceptiple,Decresed susceptiple
0,173,2020-01-22,1,0,0,1,0,0,0,339573798,339573797,19.643202,0
1,360,2020-01-23,1,0,0,1,0,0,0,339573798,339573797,19.643202,0
2,547,2020-01-24,2,0,0,2,1,0,0,339573798,339573796,19.643202,1
3,734,2020-01-25,2,0,0,2,0,0,0,339573798,339573796,19.643202,0
4,921,2020-01-26,5,0,0,5,3,0,0,339573798,339573793,19.643202,3
5,1108,2020-01-27,5,0,0,5,0,0,0,339573798,339573793,19.643202,0
6,1295,2020-01-28,5,0,0,5,0,0,0,339573798,339573793,19.643202,0
7,1482,2020-01-29,5,0,0,5,0,0,0,339573798,339573793,19.643202,0
8,1669,2020-01-30,5,0,0,5,0,0,0,339573798,339573793,19.643202,0
9,1856,2020-01-31,7,0,0,7,2,0,0,339573798,339573791,19.643202,2

In [32]:
data_us1.to_csv('./data_us.csv')