In [84]:
import covsirphy as cvp
import pandas as pd
import numpy as np

In [641]:
country = 'Singapore'

In [642]:
data = pd.read_csv('./covid_19_jhu_data_web_scrap_and_cleaning/full_grouped.csv')
data = data[data['Country/Region'] == country].reset_index()
data = data[data['Confirmed'] > 0]

In [643]:
data

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
1,337,2020-01-23,Singapore,1,0,0,1,1,0,0,Western Pacific
2,524,2020-01-24,Singapore,3,0,0,3,2,0,0,Western Pacific
3,711,2020-01-25,Singapore,3,0,0,3,0,0,0,Western Pacific
4,898,2020-01-26,Singapore,4,0,0,4,1,0,0,Western Pacific
5,1085,2020-01-27,Singapore,5,0,0,5,1,0,0,Western Pacific
...,...,...,...,...,...,...,...,...,...,...,...
174,32688,2020-07-14,Singapore,46630,27,42737,3866,347,1,196,Western Pacific
175,32875,2020-07-15,Singapore,46878,27,42988,3863,248,0,251,Western Pacific
176,33062,2020-07-16,Singapore,47126,27,43256,3843,248,0,268,Western Pacific
177,33249,2020-07-17,Singapore,47453,27,43577,3849,327,0,321,Western Pacific
178,33436,2020-07-18,Singapore,47655,27,43833,3795,202,0,256,Western Pacific

In [644]:
df = pd.read_csv('./population_2020.csv')

In [645]:
population = df[df['Country (or dependency)'] == country]['Population (2020)']

In [646]:
population = int(population)
print(population)

5840996

In [647]:
num_sample = len(data)

In [648]:
population = [population for _ in range(num_sample)]

In [649]:
data['Population'] = population

In [650]:
data.tail()

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population
174,32688,2020-07-14,Singapore,46630,27,42737,3866,347,1,196,Western Pacific,5840996
175,32875,2020-07-15,Singapore,46878,27,42988,3863,248,0,251,Western Pacific,5840996
176,33062,2020-07-16,Singapore,47126,27,43256,3843,248,0,268,Western Pacific,5840996
177,33249,2020-07-17,Singapore,47453,27,43577,3849,327,0,321,Western Pacific,5840996
178,33436,2020-07-18,Singapore,47655,27,43833,3795,202,0,256,Western Pacific,5840996

In [651]:
data['Susceptiple'] = data['Population'] - data['Confirmed']

In [652]:
data['Log susceptiple'] = np.log(data['Susceptiple'])

In [653]:
data.tail()

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population,Susceptiple,Log susceptiple
174,32688,2020-07-14,Singapore,46630,27,42737,3866,347,1,196,Western Pacific,5840996,5794366,15.572397
175,32875,2020-07-15,Singapore,46878,27,42988,3863,248,0,251,Western Pacific,5840996,5794118,15.572354
176,33062,2020-07-16,Singapore,47126,27,43256,3843,248,0,268,Western Pacific,5840996,5793870,15.572311
177,33249,2020-07-17,Singapore,47453,27,43577,3849,327,0,321,Western Pacific,5840996,5793543,15.572255
178,33436,2020-07-18,Singapore,47655,27,43833,3795,202,0,256,Western Pacific,5840996,5793341,15.572220

In [654]:
susceptiple = np.asarray(data['Susceptiple'])

In [655]:
new_susceptiple = susceptiple[:-1] - susceptiple[1:]

In [656]:
new_susceptiple = np.insert(new_susceptiple, 0, 0)

In [657]:
data['Decresed susceptiple'] = new_susceptiple

In [658]:
data.head(100)

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population,Susceptiple,Log susceptiple,Decresed susceptiple
1,337,2020-01-23,Singapore,1,0,0,1,1,0,0,Western Pacific,5840996,5840995,15.580412,0
2,524,2020-01-24,Singapore,3,0,0,3,2,0,0,Western Pacific,5840996,5840993,15.580411,2
3,711,2020-01-25,Singapore,3,0,0,3,0,0,0,Western Pacific,5840996,5840993,15.580411,0
4,898,2020-01-26,Singapore,4,0,0,4,1,0,0,Western Pacific,5840996,5840992,15.580411,1
5,1085,2020-01-27,Singapore,5,0,0,5,1,0,0,Western Pacific,5840996,5840991,15.580411,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,18102,2020-04-27,Singapore,14423,14,1095,13314,799,2,35,Western Pacific,5840996,5826573,15.577940,799
97,18289,2020-04-28,Singapore,14951,14,1128,13809,528,0,33,Western Pacific,5840996,5826045,15.577849,528
98,18476,2020-04-29,Singapore,15641,14,1188,14439,690,0,60,Western Pacific,5840996,5825355,15.577730,690
99,18663,2020-04-30,Singapore,16169,15,1244,14910,528,1,56,Western Pacific,5840996,5824827,15.577640,528
100,18850,2020-05-01,Singapore,17101,16,1268,15817,932,1,24,Western Pacific,5840996,5823895,15.577480,932

In [659]:
data = data.drop(columns=['WHO Region', 'Country/Region', 'index'])

In [660]:
data.head(10)

,Date,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Population,Susceptiple,Log susceptiple,Decresed susceptiple
1,2020-01-23,1,0,0,1,1,0,0,5840996,5840995,15.580412,0
2,2020-01-24,3,0,0,3,2,0,0,5840996,5840993,15.580411,2
3,2020-01-25,3,0,0,3,0,0,0,5840996,5840993,15.580411,0
4,2020-01-26,4,0,0,4,1,0,0,5840996,5840992,15.580411,1
5,2020-01-27,5,0,0,5,1,0,0,5840996,5840991,15.580411,1
6,2020-01-28,7,0,0,7,2,0,0,5840996,5840989,15.580411,2
7,2020-01-29,7,0,0,7,0,0,0,5840996,5840989,15.580411,0
8,2020-01-30,10,0,0,10,3,0,0,5840996,5840986,15.580410,3
9,2020-01-31,13,0,0,13,3,0,0,5840996,5840983,15.580410,3
10,2020-02-01,16,0,0,16,3,0,0,5840996,5840980,15.580409,3

In [661]:
data.to_csv(country+'.csv')