In [50]:
import covsirphy as cvp
import pandas as pd
import numpy as np

In [51]:
country = 'Vietnam'

In [52]:
data = pd.read_csv('./covid_19_jhu_data_web_scrap_and_cleaning/full_grouped.csv')
data = data[data['Country/Region'] == country].reset_index()
data = data[data['Confirmed'] > 0]

In [53]:
data = data.fillna(0)

In [54]:
df = pd.read_csv('./population_2020.csv')

In [55]:
population = df[df['Country (or dependency)'] == country]['Population (2020)']

In [56]:
population = int(population)
print(population)

97160127

In [57]:
num_sample = len(data)

In [58]:
population = [population for _ in range(num_sample)]

In [59]:
data['Population'] = population

In [60]:
data.tail()

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population
183,34402,2020-07-23,Vietnam,412,0,365,47,4,0,0,Western Pacific,97160127
184,34589,2020-07-24,Vietnam,415,0,365,50,3,0,0,Western Pacific,97160127
185,34776,2020-07-25,Vietnam,417,0,365,52,2,0,0,Western Pacific,97160127
186,34963,2020-07-26,Vietnam,420,0,365,55,3,0,0,Western Pacific,97160127
187,35150,2020-07-27,Vietnam,431,0,365,66,11,0,0,Western Pacific,97160127

In [61]:
data['Susceptiple'] = data['Population'] - data['Confirmed']

In [62]:
data['Log susceptiple'] = np.log(data['Susceptiple'])

In [63]:
data.tail()

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population,Susceptiple,Log susceptiple
183,34402,2020-07-23,Vietnam,412,0,365,47,4,0,0,Western Pacific,97160127,97159715,18.391867
184,34589,2020-07-24,Vietnam,415,0,365,50,3,0,0,Western Pacific,97160127,97159712,18.391867
185,34776,2020-07-25,Vietnam,417,0,365,52,2,0,0,Western Pacific,97160127,97159710,18.391867
186,34963,2020-07-26,Vietnam,420,0,365,55,3,0,0,Western Pacific,97160127,97159707,18.391867
187,35150,2020-07-27,Vietnam,431,0,365,66,11,0,0,Western Pacific,97160127,97159696,18.391867

In [64]:
susceptiple = np.asarray(data['Susceptiple'])

In [65]:
new_susceptiple = susceptiple[:-1] - susceptiple[1:]

In [66]:
new_susceptiple = np.insert(new_susceptiple, 0, 0)

In [67]:
data['Decresed susceptiple'] = new_susceptiple

In [68]:
data.head(100)

,index,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region,Population,Susceptiple,Log susceptiple,Decresed susceptiple
1,368,2020-01-23,Vietnam,2,0,0,2,2,0,0,Western Pacific,97160127,97160125,18.391871,0
2,555,2020-01-24,Vietnam,2,0,0,2,0,0,0,Western Pacific,97160127,97160125,18.391871,0
3,742,2020-01-25,Vietnam,2,0,0,2,0,0,0,Western Pacific,97160127,97160125,18.391871,0
4,929,2020-01-26,Vietnam,2,0,0,2,0,0,0,Western Pacific,97160127,97160125,18.391871,0
5,1116,2020-01-27,Vietnam,2,0,0,2,0,0,0,Western Pacific,97160127,97160125,18.391871,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,18133,2020-04-27,Vietnam,270,0,225,45,0,0,0,Western Pacific,97160127,97159857,18.391868,0
97,18320,2020-04-28,Vietnam,270,0,222,48,0,0,-3,Western Pacific,97160127,97159857,18.391868,0
98,18507,2020-04-29,Vietnam,270,0,222,48,0,0,0,Western Pacific,97160127,97159857,18.391868,0
99,18694,2020-04-30,Vietnam,270,0,219,51,0,0,-3,Western Pacific,97160127,97159857,18.391868,0
100,18881,2020-05-01,Vietnam,270,0,219,51,0,0,0,Western Pacific,97160127,97159857,18.391868,0

In [69]:
data = data.drop(columns=['WHO Region', 'Country/Region', 'index'])

In [70]:
data.head(10)

,Date,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Population,Susceptiple,Log susceptiple,Decresed susceptiple
1,2020-01-23,2,0,0,2,2,0,0,97160127,97160125,18.391871,0
2,2020-01-24,2,0,0,2,0,0,0,97160127,97160125,18.391871,0
3,2020-01-25,2,0,0,2,0,0,0,97160127,97160125,18.391871,0
4,2020-01-26,2,0,0,2,0,0,0,97160127,97160125,18.391871,0
5,2020-01-27,2,0,0,2,0,0,0,97160127,97160125,18.391871,0
6,2020-01-28,2,0,0,2,0,0,0,97160127,97160125,18.391871,0
7,2020-01-29,2,0,0,2,0,0,0,97160127,97160125,18.391871,0
8,2020-01-30,2,0,0,2,0,0,0,97160127,97160125,18.391871,0
9,2020-01-31,2,0,0,2,0,0,0,97160127,97160125,18.391871,0
10,2020-02-01,6,0,1,5,4,0,1,97160127,97160121,18.391871,4

In [71]:
data.to_csv(country+'.csv')